// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDlFw2cM5Wf4gbIUfHOFDzuax4iVY6BU',
    appId: '1:625300340169:web:fab8a2dad37fd29aa73c18',
    messagingSenderId: '625300340169',
    projectId: 'to-gether-gun-game',
    authDomain: 'to-gether-gun-game.firebaseapp.com',
    storageBucket: 'to-gether-gun-game.appspot.com',
    measurementId: 'G-R37YG78KY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrSKr7mxqNu5qFwkqy-pIRb7xB00SHpcY',
    appId: '1:625300340169:android:270ed582c3d1166ba73c18',
    messagingSenderId: '625300340169',
    projectId: 'to-gether-gun-game',
    storageBucket: 'to-gether-gun-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNFlFY9lbMMWUo3mf3qe6eZBGE38TG6c',
    appId: '1:625300340169:ios:254668e2d566ad50a73c18',
    messagingSenderId: '625300340169',
    projectId: 'to-gether-gun-game',
    storageBucket: 'to-gether-gun-game.appspot.com',
    androidClientId: '625300340169-ddpqotln6v820ci2bdj0gmmnfda85jea.apps.googleusercontent.com',
    iosClientId: '625300340169-ah3foule1rsmqcn8v108l56c517b6s1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.toGetherGunGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNFlFY9lbMMWUo3mf3qe6eZBGE38TG6c',
    appId: '1:625300340169:ios:254668e2d566ad50a73c18',
    messagingSenderId: '625300340169',
    projectId: 'to-gether-gun-game',
    storageBucket: 'to-gether-gun-game.appspot.com',
    androidClientId: '625300340169-ddpqotln6v820ci2bdj0gmmnfda85jea.apps.googleusercontent.com',
    iosClientId: '625300340169-ah3foule1rsmqcn8v108l56c517b6s1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.toGetherGunGame',
  );
}
